python -m franka_control_client.policy.pi05_policy_node \
    --checkpoint_path /hkfs/work/workspace/scratch/utphd-myspace/outputs/pi05_bs256_10ksteps_fixed_index/checkpoints/010000/pretrained_model \
    --dataset_path /hkfs/work/workspace/scratch/utphd-myspace/datasets/cylinder_cube_full \
    --device cuda \
    --policy_dtype bfloat16 \
    --obs_topic pi05/observation \
    --action_topic pi05/action \
    --fps 20 \
    --default_task "put green cylinder on blue cube" \
    --direct_zmq_bind tcp://0.0.0.0:40023 \
    --rtc_enabled \
    --rtc_execution_horizon 25 \
    --rtc_max_guidance_weight 5.0 \
    --rtc_prefix_attention_schedule exp
