python -m franka_control_client.policy.pi05_policy_node \
    --checkpoint_path /home/jjiang/utphd/pretrained_model \
    --dataset_path /home/jjiang/jing/dataset/lerobot/cylinder_full \
    --device cuda \
    --policy_dtype bfloat16 \
    --obs_topic pi05/observation \
    --action_topic pi05/action \
    --fps 20 \
    --default_task "Put the yellow block on the blue block." \
    --pyzlc_host 0.0.0.0 \
    --pyzlc_group_name DroidGroup \
    --pyzlc_group_port 7730
